development:
  adapter: postgresql
  database: makingskincare_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: makingskincare_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: makingskincare_production
  pool: 5
  timeout: 5000
